### ISSUE TITLE
question on input labelled documents

### ISSUE THREAD

**Issue by phamsonit** [JoeZJH/Labeled-LDA-Python#5]
Dear,

First of all, thank you very much for your sharing a nice program.

I have a question related to the input labeled documents as follow
Each document has a following number, for example, labeled_documents = [("text" * 10, ['label_1]), ...],. In this case, what is 10 used for? How does it affect the training process? For example, if we change these values or even ignore them.

Thank you very much in advance!
Best regards,
Son.

**Comment by JoeZJH** [comment]
Dear, 

Sorry, my laziness interferes with your judgment of the code.

 In code snippet `labeled_documents = [("text " * 10, ['label_1]), ...]`, `"text " * 10` means "text text text text text text text text text text ", in other words, 10 just a number of "text " repetitions, I just want to save time with the code `"text " * 10` .

Thanks for your question.
Best wishes,
Joe

**Comment by phamsonit** [comment]
Thank you very much for your quick response!
Best regards,
Son.
